eureka:
  client:
    serviceUrl:
      defaultZone: ${discovery-service-uri}
  instance:
    prefer-ip-address: true

spring:
  data:
    mongodb:
      uri: mongodb+srv://${spring.datasource.username}:${spring.datasource.password}@test.bzk8n3u.mongodb.net/files

logging:
  level:
    root: INFO
    web: INFO
    org:
      springframework:
        security: INFO
    reactor:
      netty:
        http: INFO