package io.complyt.authentication.business.authorization;

import io.complyt.authentication.business.authorization.Wrappers.AccessTokenAuthorizationServerWrapper;
import io.complyt.authentication.business.authorization.Wrappers.ApiKeyRevocationAuthorinzationServerWrapper;
import io.complyt.authentication.business.authorization.Wrappers.ManagementAuthorizationServerWrapper;
import io.complyt.authentication.business.authorization.Wrappers.TenantIdAndNameAuthorizationServerWrapper;


public interface AuthorizationServerWrapper extends AccessTokenAuthorizationServerWrapper, ApiKeyRevocationAuthorinzationServerWrapper,
        ManagementAuthorizationServerWrapper, TenantIdAndNameAuthorizationServerWrapper {

}
