spring.application.name: authentication
server.port: ${PORT:9860}

spring.profiles.active:
  - @activeEnv@
  - @activeAuthorizationServer@

# Observability
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.tracing.sampling.probability: 1.0

spring:
  data:
    mongodb:
      uuid-representation: standard

cryption.secret-key: ${secret-key}
token-service.token-expiration-safe-window-sec: ${token-expiration-safe-window-sec}
authorization:
  issuer-uri: ${issuer-uri}
  grant-type: ${grant-type}
  audience: ${audience}
  authorization-server-url: ${authorization-server-url}