@startuml
'https://plantuml.com/sequence-diagram

autonumber

DtoHandler -> DtoValidation: handle

DtoValidation --> ValidationHandler: handle

rnote over ValidationHandler
Handle Function
endrnote

ValidationHandler -> PathProvider: validatePath
alt#Gold #LightBlue Successful case
    PathProvider -> ValidationHandler: true
else #Pink Failure
    PathProvider -> ValidationHandler: PathVariableExcepption
end

ValidationHandler -> ParamProvider: validateParam
alt#Gold #LightBlue Successful case
    ParamProvider -> ValidationHandler: true
else #Pink Failure
    ParamProvider -> ValidationHandler: QueryParamExcepption
end


ValidationHandler -> ExtractDto : extractDto
ExtractDto -> ValidationHandler: generalDto



ValidationHandler -> DtoValidation : DtoBody

@enduml