@startuml
'https://plantuml.com/sequence-diagram

autonumber

DtoHandler -> ValidationHandler: handle


rnote over ValidationHandler
Handle Function
endrnote


ValidationHandler -> PathProvider: validatePath
note right
  Applies
  the PathFunctions
  on param
end note

alt#Gold #LightBlue Successful case
    PathProvider -> ValidationHandler: Mono.just(true)
else #Pink Failure
    PathProvider -> ValidationHandler: PathVariableException
end


ValidationHandler -> ParamProvider: validateParam
note right
  Applies
  the QueryFunctions
  on param
end note
alt#Gold #LightBlue Successful case
    ParamProvider -> ValidationHandler: Mono.just(true)
else #Pink Failure
    ParamProvider -> ValidationHandler: QueryParamExcepption
end



ValidationHandler -> BodyProvider : isBodyEmpty
note right
  Uses
  headers.contentLength
end note
BodyProvider [#00ff00]-> ValidationHandler: Mono.just(true)


ValidationHandler -[#0000FF]-> DtoHandler : Mono.empty()

@enduml