server:
  port: 8765

spring:
  application:
    name: api-gateway
  profiles:
    active:
    - @activeEnv@
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      metrics.enabled: true
      routes:
      # ==== Sales Tax Service ====
      # ---- Transaction ----
      - id: sales-tax-get-transactions
        uri: lb://sales-tax
        predicates:
          - Method=GET
          - Path=/v1/transactions
        filters:
          - SetPath=/v1/transactions
      - id: sales-tax-get-transaction-by-external-id
        uri: lb://sales-tax
        predicates:
          - Method=GET
          - Path=/v1/transactions/{segment}
        filters:
          - SetPath=/v1/transactions/{segment}
      - id: sales-tax-get-transaction-by-external-id
        uri: lb://sales-tax
        predicates:
          - Method=GET
          - Path=/v1/transactions/{segment}
        filters:
          - SetPath=/v1/transactions/{segment}
      - id: sales-tax-put-transaction
        uri: lb://sales-tax
        predicates:
          - Method=PUT
          - Path=/v1/transactions/{segment}
        filters:
          - SetPath=/v1/transactions/{segment}
      - id: sales-tax-delete-transaction
        uri: lb://sales-tax
        predicates:
          - Method=DELETE
          - Path=/v1/transactions/{segment}
        filters:
          - SetPath=/v1/transactions/{segment}
      # ---- Transaction ----
      # ---- Customer ----
      - id: sales-tax-get-customers
        uri: lb://sales-tax
        predicates:
          - Method=GET
          - Path=/v1/customers
        filters:
          - SetPath=/v1/customers
      - id: sales-tax-get-customer-by-name
        uri: lb://sales-tax
        predicates:
          - Method=GET
          - Path=/v1/customers/name/{name}
        filters:
          - SetPath=/v1/customers/name/{name}
      - id: sales-tax-get-customer-by-external-id
        uri: lb://sales-tax
        predicates:
          - Method=GET
          - Path=/v1/customers/{segment}
        filters:
          - SetPath=/v1/customers/{segment}
      - id: sales-tax-put-customer
        uri: lb://sales-tax
        predicates:
          - Method=PUT
          - Path=/v1/customers/{segment}
        filters:
          - SetPath=/v1/customers/{segment}
      - id: sales-tax-post-customer
        uri: lb://sales-tax
        predicates:
          - Method=POST
          - Path=/v1/customers
        filters:
          - SetPath=/v1/customers
      # ---- Customer ----
      # ==== Sales Tax Service ====