spring:
  security.oauth2.resourceserver.jwt.issuer-uri: https://development-complyt.us.auth0.com/
  cloud:
    vault:
      enabled: false
    gateway:
      routes:
        # ==== Test Service ====
        - id: test-app-hi
          uri: lb://test-application
          predicates:
            - Method=GET
            - Path=/hi
          filters:
            - SetPath=/hi
        # ==== Test Service ====

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management.endpoints.web.exposure.include: "*"

auth0.audience: https://sales-tax-service/