spring:
  security.oauth2.resourceserver.jwt.issuer-uri: https://development-complyt.us.auth0.com/
  cloud:
    vault:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management.endpoints.web.exposure.include: "*"

auth0.audience: https://sales-tax-service/