#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${discovery-service-uri}
#  instance:
#    prefer-ip-address: true

eureka:
  client:
    #    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - name: files
        url: /v3/api-docs/files
      - name: sales-tax
        url: /v3/api-docs/sales-tax
  api-docs:
    version: openapi_3_0