# MongoDB properties
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=complyt

#Heroku
spring.data.mongodb.uri=mongodb+srv://admin:admin@cluster0.tlaie.mongodb.net/complyt
server.port=8687
#server.port=${PORT:8687}