#logging.level.web=DEBUG
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
spring.data.mongodb.uri=mongodb+srv://admin:admin@cluster0.tlaie.mongodb.net/complyt
#server.port=${PORT:9898}
#MongoDB properties
#spring.data.mongodb.host=cluster0.tlaie.mongodb.net
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=complyt


#Heroku
