spring:
  profiles:
    active:
      - production
      # fastTax - to use FastTax service
      # stubFastTax - to use stub method of FastTax
      # zipTax - to use Zip Tax Service
      - fastTax
  security:
    user:
      name: complyt
      password: "$2a$10$nhBTPIQr1O6NJHPJKpVA5eQp3kYFojjbi09CAmT9xd7GW7v2tGlaS"

logging:
  level:
    root: INFO
    web: DEBUG
    org:
      springframework:
        security: DEBUG
    reactor:
      netty:
        http: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"



