spring:
  profiles:
    active:
      - production
      # fastTax - to use FastTax service
      # stubFastTax - to use stub method of FastTax
      # zipTax - to use Zip Tax Service
      - fastTax

logging:
  level:
    root: INFO
    web: DEBUG
    org:
      springframework:
        security: DEBUG
    reactor:
      netty:
        http: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"



