spring.application.name: address-validation
server.port: ${PORT:9850}

spring.profiles.active:
  - @activeEnv@
  - @activeAddressValidationClient@

# Observability
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.tracing.sampling.probability: 1.0

spring:
  data:
    mongodb:
      uuid-representation: standard