version: 2.1

workflows:
  build-test-deploy:
    jobs:
      - verify

      - deploy:
          filters:
            branches:
              only:
                - main

      - send-test-coverage-reports:
          requires:
            - verify
            - deploy

      - update-ecs-service:
          filters:
            branches:
              only:
                - main
          requires:
            - deploy

orbs:
  codecov: codecov/codecov@3.0.0
  aws-cli: circleci/aws-cli@1.3
  aws-ecs: circleci/aws-ecs@2.0

executors:
  ubuntu-vm:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    working_directory: ~/complyt_work_directory

  openjdk-image:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/complyt_work_directory

  python-image:
    docker:
      - image: 'cimg/python:3.9.1'
    working_directory: ~/complyt_work_directory

jobs:
  verify:
    executor: ubuntu-vm
    steps:
      - checkout
      - run:
          name: Build
          command: ./mvnw clean verify
      - persist_to_workspace:
          root: target
          paths:
            - surefire-reports/*
            - jacoco-reports/*
            - failsafe-reports/*
            - site/*
            - jacoco.exec

  deploy:
    executor: ubuntu-vm
    steps:
      - checkout
      - run:
          name: Avoid hosts unknown for github
          command: echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - add_ssh_keys:
          fingerprints:
            - "d1:1b:cb:32:11:5d:0e:bc:67:c7:25:0f:ca:41:57:b1"
      - run:
          name: Setup Git credentials user email
          command: git config user.email "alexander@complyt.io"

      - run:
          name: Setup Git credentials user name
          command: git config user.name "Via CircleCI Build"

      - run:
          name: Creating Maven settings-security.xml file
          command: echo "<settingsSecurity><master>${MAVEN_SECURITY_MASTER}</master></settingsSecurity>" > ~/.m2/settings-security.xml

      - run:
          name: Release a Production Version
          command: ./mvnw --settings .circleci/settings.xml --batch-mode release:clean release:prepare release:perform

  send-test-coverage-reports:
    executor: openjdk-image
    steps:
      - attach_workspace:
          at: ~/complyt_work_directory
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/ \;
          when: always
      - store_test_results:
          path: '~/test-results/'
      - codecov/upload:
          file: '/home/circleci/complyt_work_directory/target/jacoco-reports/jacoco.xml'
          token: CODECOV_TOKEN

  update-ecs-service:
    executor: python-image
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - aws-ecs/update-service:
          cluster-name: 'Complyt'
          container-image-name-updates: 'container=Complyt,tag=latest'
          family: 'Complyt'
          service-name: 'Complyt-ECS-Fargate-LB'