version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
  test:
      docker: 
        - image: cimg/openjdk:11.0
      steps:
      - checkout
      - run:
          name: Test
          command: mvn test
  code_coverage:
      docker: 
        - image: cimg/openjdk:11.0
      steps:
        - checkout
        - codecov/upload:
            file: '/target/jacoco-reports/jacoco.xml'
            token: CODECOV_TOKEN

workflows:
  build-test-code_coverage:
    jobs:
      - build
      - test:
          requires:
          - build
      - code_coverage:
          requires:
          - test