version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.0.2

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: main
          mapping: |
            sales-tax/.* run-sales-tax-workflow true
            files/.* run-files-workflow true
            api-gateway/.* run-api-gateway-workflow true
            discovery-service/.* run-discovery-service-workflow true
            sales-tax-rates/.* run-sales-tax-rates-workflow true
          config-path: .circleci/workflows.yml

      - deploy-job:
          steps:
            - add_ssh_keys:
                fingerprints:
                  - "7f:28:78:67:0b:ff:ff:c9:f3:87:8c:4c:6a:3e:d0:81"
