orbs:
  codecov: codecov/codecov@4.1.0
  aws-cli: circleci/aws-cli@4.1.3
  aws-ecs: circleci/aws-ecs@4.0.0

version: 2.1

executors:
  ubuntu-vm:
    machine:
      image: ubuntu-2204:2022.07.1
      docker_layer_caching: true

  openjdk-image:
    docker:
      - image: cimg/openjdk:11.0

  python-image:
    docker:
      - image: 'cimg/python:3.9.1'

  arm64-ubuntu-22-lts-corretto-21-vm:
    machine: true
    resource_class: complyt/arm64-ubuntu-22-lts-corretto-21

  arm64-ubuntu-22-lts-corretto-21-vm-gcp:
    machine: true
    resource_class: complyt/arm64-ubuntu-22-lts-corretto-21-gcp

parameters:
  run-sales-tax-workflow:
    type: boolean
    default: false
  run-files-workflow:
    type: boolean
    default: false
  run-api-gateway-workflow:
    type: boolean
    default: false
  run-discovery-service-workflow:
    type: boolean
    default: false
  run-address-validation-workflow:
    type: boolean
    default: false
  run-sales-tax-rates-workflow:
    type: boolean
    default: false
  run-authentication-workflow:
    type: boolean
    default: false
  run-api-gateway-verify-workflow:
    type: boolean
    default: false

jobs:
  package-dependency:
    parameters:
      service_directory:
        type: string
        default: ""

    executor: arm64-ubuntu-22-lts-corretto-21-vm
    steps:
      - checkout
      - run:
          name: Execute
          command: |
            cd <<parameters.service_directory>>
            ./mvnw clean package -Dmaven.test.skip
      - persist_to_workspace:
          root: .
          paths:
            - <<parameters.service_directory>>/target/*.jar

  package-dependency-for-gateway:
    parameters:
      service_directory:
        type: string
        default: ""

    executor: arm64-ubuntu-22-lts-corretto-21-vm-gcp
    steps:
      - checkout
      - run:
          name: Execute
          command: |
            cd <<parameters.service_directory>>
            ./mvnw clean package -Dmaven.test.skip
      - persist_to_workspace:
          root: .
          paths:
            - <<parameters.service_directory>>/target/*.jar

  verify:
    parameters:
      service_directory:
        type: string
        default: ""

    executor: arm64-ubuntu-22-lts-corretto-21-vm
    steps:
      - checkout
      #We must use attach_workspace to gain access to the artifacts that we build on previous steps (of our services)
      - attach_workspace:
          at: .
      - run:
          name: Execute
          command: |
            cd <<parameters.service_directory>>
            ./mvnw clean verify

      - persist_to_workspace:
          root: <<parameters.service_directory>>/target
          paths:
            - coverage-reports
            - failsafe-reports
            - surefire-reports
            - site

  verify-gateway:
    parameters:
      service_directory:
        type: string
        default: ""

    executor: arm64-ubuntu-22-lts-corretto-21-vm-gcp
    steps:
      - checkout
      #We must use attach_workspace to gain access to the artifacts that we build on previous steps (of our services)
      - attach_workspace:
          at: .
      - run:
          name: Execute
          command: |
            cd <<parameters.service_directory>>
            ./mvnw clean verify

      - persist_to_workspace:
          root: <<parameters.service_directory>>/target
          paths:
            - coverage-reports
            - failsafe-reports
            - surefire-reports
            - site

  release:
    parameters:
      service_directory:
        type: string
        default: ""

    executor: arm64-ubuntu-22-lts-corretto-21-vm
    steps:
      - checkout
      #We must use attach_workspace to gain access to the artifacts that we build on previous steps (of our services)
      - attach_workspace:
          at: .

      - add_ssh_keys:
          fingerprints:
            - "8d:a9:53:20:ea:7a:b2:1d:e5:d8:af:d4:fc:e0:81:16"

      - run:
          name: Export Environment variables for access to image_tag
          command: |
            cd <<parameters.service_directory>>
            image_tag=$(grep -m2 '<version>' pom.xml | tail -n1 | sed -n 's/.*<version>\([0-9.]*\).*<\/version>.*/\1/p')
            export IMAGE_TAG=$image_tag
            env >> bash.env

      - run:
          name: Release
          command: |
            env
            cd <<parameters.service_directory>>
            PROJECT_VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
            NEXT_DEVELOPMENT_VERSION=$(echo "$PROJECT_VERSION" | awk -F'[-.]' '{print $1"."($2+1)".0-SNAPSHOT"}')
            git checkout -b "<<parameters.service_directory>>-$PROJECT_VERSION"
            ./mvnw --settings ../.circleci/settings.xml clean release:prepare -X -DdevelopmentVersion=$NEXT_DEVELOPMENT_VERSION
            ./mvnw --settings ../.circleci/settings.xml release:perform
            bash ../.circleci/git_commands.sh <<parameters.service_directory>> "$PROJECT_VERSION"

      - persist_to_workspace:
          root: ./<<parameters.service_directory>>
          paths:
            - bash.env

      - persist_to_workspace:
          root: <<parameters.service_directory>>/target
          paths:
            - coverage-test-service
            - failsafe-test-service
            - surefire-test-service
            - site

      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          region: AWS_DEFAULT_REGION
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY

      - run:
          name: Build and push docker image to ecr
          command: |
            env
            cd <<parameters.service_directory>>
            export DOCKERFILE_PATH="target/dockerfile/Dockerfile"
            export SEARCH_PATTERN="ADD maven/"
            export REPLACE_PATTERN="ADD target/"
            SERVICE_NAME=$(basename "<<parameters.service_directory>>")
            export IMAGE_TAG="096643436058.dkr.ecr.us-east-1.amazonaws.com/complyt/$SERVICE_NAME:$IMAGE_TAG"
            sed -i "s|$SEARCH_PATTERN|$REPLACE_PATTERN|g" "$DOCKERFILE_PATH"
            docker build -f "$DOCKERFILE_PATH" -t "$IMAGE_TAG" .
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 096643436058.dkr.ecr.us-east-1.amazonaws.com
            docker push "$IMAGE_TAG"

  send-test-coverage-reports:
    parameters:
      service_directory:
        type: string
        default: ""

    executor: openjdk-image
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Save test results
          command: |
            mkdir -p test-results/junit/
            find . -type f -regex ".*/surefire-reports/.*xml" -exec cp {} ./test-results/junit/ \;
          when: always
      - store_test_results:
          path: ./test-results
      - codecov/upload:
          file: site/jacoco-ut/jacoco.xml
          token: CODECOV_TOKEN
          flags: <<parameters.service_directory>>

  update-ecs-service:
    parameters:
      service_name:
        type: string
        default: ""

    executor: python-image
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Set image tag as env variable
          command: |
            image_tag=$(grep "IMAGE_TAG" bash.env | cut -d'=' -f2)
            echo "container=<<parameters.service_name>>, tag='${image_tag}'"
            echo "export IMAGE_TAG='${image_tag}'" >> $BASH_ENV
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          region: AWS_DEFAULT_REGION
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
      
      ## Deploy to production cluster
      - aws-ecs/update_service:
          cluster: "prod-1"
          container_image_name_updates: "container=<<parameters.service_name>>, tag=${IMAGE_TAG}"
          family: "<<parameters.service_name>>-prod-1"
          service_name: "<<parameters.service_name>>"
      ## Deploy to production ec2 cluster
      - aws-ecs/update_service:
          cluster: "prod-2-ec2"
          container_image_name_updates: "container=<<parameters.service_name>>, tag=${IMAGE_TAG}"
          family: "<<parameters.service_name>>-prod-2"
          service_name: "<<parameters.service_name>>"
      ## Deploy to demo cluster
      - aws-ecs/update_service:
          cluster: "demo-1"
          container_image_name_updates: "container=<<parameters.service_name>>, tag=latest"
          family: "<<parameters.service_name>>-demo-1"
          service_name: "<<parameters.service_name>>"
      ## Deploy to sandbox cluster
      - aws-ecs/update_service:
          cluster: "sandbox-1"
          container_image_name_updates: "container=<<parameters.service_name>>, tag=latest"
          family: "<<parameters.service_name>>-sandbox-1"
          service_name: "<<parameters.service_name>>"
      ## Deploy to assessment cluster
      - aws-ecs/update_service:
          cluster: "assessment"
          container_image_name_updates: "container=<<parameters.service_name>>, tag=latest"
          family: "<<parameters.service_name>>-assessment"
          service_name: "<<parameters.service_name>>"

workflows:
  sales-tax-workflow:
    when: << pipeline.parameters.run-sales-tax-workflow >>
    jobs:
      - verify:
          filters:
            branches:
              only:
                - /^(main.+|(?!main).*)$/
          service_directory: "sales-tax"

      - release:
          service_directory: "sales-tax"
          filters:
            branches:
              only:
                - main

      - send-test-coverage-reports:
          requires:
            - verify
            - release
          service_directory: "sales-tax"

      - update-ecs-service:
          requires:
            - release
          service_name: "sales-tax"

  files-workflow:
    when: << pipeline.parameters.run-files-workflow >>
    jobs:
      - verify:
          filters:
            branches:
              only:
                - /^(main.+|(?!main).*)$/
          service_directory: "files"

      - release:
          service_directory: "files"
          filters:
            branches:
              only:
                - main

      - send-test-coverage-reports:
          requires:
            - verify
            - release
          service_directory: "files"

      - update-ecs-service:
          requires:
            - release
          service_name: "files"

  address-validation-workflow:
    when: << pipeline.parameters.run-address-validation-workflow >>
    jobs:
      - verify:
          filters:
            branches:
              only:
                - /^(main.+|(?!main).*)$/
          service_directory: "address-validation"

      - release:
          service_directory: "address-validation"
          filters:
            branches:
              only:
                - main

      - send-test-coverage-reports:
          requires:
            - verify
            - release
          service_directory: "address-validation"

      - update-ecs-service:
          requires:
            - release
          service_name: "address-validation"

  api-gateway-workflow:
    when: << pipeline.parameters.run-api-gateway-workflow >>
    jobs:
      - package-dependency:
          name: package-sales-tax
          service_directory: "sales-tax"
      - package-dependency:
          name: package-sales-tax-rates
          service_directory: "sales-tax-rates"
      - package-dependency:
          name: package-address-validation
          service_directory: "address-validation"
      - package-dependency:
          name: package-discovery-service
          service_directory: "discovery-service"
      - package-dependency:
          name: package-files
          service_directory: "files"
      - package-dependency:
          name: package-authentication
          service_directory: "authentication"

      - verify:
          filters:
            branches:
              only:
                - /^(main.+|(?!main).*)$/
          requires:
            - package-sales-tax
            - package-sales-tax-rates
            - package-address-validation
            - package-discovery-service
            - package-files
            - package-authentication
          service_directory: "api-gateway"

      - release:
          requires:
            - package-sales-tax
            - package-sales-tax-rates
            - package-address-validation
            - package-discovery-service
            - package-files
            - package-authentication
          filters:
            branches:
              only:
                - main
          service_directory: "api-gateway"

      - send-test-coverage-reports:
          requires:
            - verify
            - release
          service_directory: "api-gateway"

      - update-ecs-service:
          requires:
            - release
          service_name: "api-gateway"

  api-gateway-verify-workflow:
    when: << pipeline.parameters.run-api-gateway-verify-workflow >>
    jobs:
      - package-dependency-for-gateway:
          name: package-sales-tax
          service_directory: "sales-tax"
      - package-dependency-for-gateway:
          name: package-sales-tax-rates
          service_directory: "sales-tax-rates"
      - package-dependency-for-gateway:
          name: package-address-validation
          service_directory: "address-validation"
      - package-dependency-for-gateway:
          name: package-discovery-service
          service_directory: "discovery-service"
      - package-dependency-for-gateway:
          name: package-files
          service_directory: "files"
      - package-dependency-for-gateway:
          name: package-authentication
          service_directory: "authentication"

      - verify-gateway:
          filters:
            branches:
              only:
                - /^(main.+|(?!main).*)$/
          requires:
            - package-sales-tax
            - package-sales-tax-rates
            - package-address-validation
            - package-discovery-service
            - package-files
            - package-authentication
          service_directory: "api-gateway"

  discovery-service-workflow:
    when: << pipeline.parameters.run-discovery-service-workflow >>
    jobs:
      - verify:
          filters:
            branches:
              only:
                - /^(main.+|(?!main).*)$/
          service_directory: "discovery-service"

      - release:
          filters:
            branches:
              only:
                - main
          service_directory: "discovery-service"

      - send-test-coverage-reports:
          requires:
            - verify
            - release
          service_directory: "discovery-service"

      # We update all the services that run Discovery Services
      - update-ecs-service:
          requires:
            - release
          service_name: "discovery-az-1a"

      - update-ecs-service:
          requires:
            - release
          service_name: "discovery-az-1b"

  sales-tax-rates-workflow:
    when: << pipeline.parameters.run-sales-tax-rates-workflow >>
    jobs:
      - verify:
          filters:
            branches:
              only:
                - /^(main.+|(?!main).*)$/
          service_directory: "sales-tax-rates"

      - release:
          filters:
            branches:
              only:
                - main
          service_directory: "sales-tax-rates"

      - send-test-coverage-reports:
          requires:
            - verify
            - release
          service_directory: "sales-tax-rates"

      - update-ecs-service:
          requires:
            - release
          service_name: "sales-tax-rates"

  authentication-workflow:
    when: << pipeline.parameters.run-authentication-workflow >>
    jobs:
      - verify:
          filters:
            branches:
              only:
                - /^(main.+|(?!main).*)$/
          service_directory: "authentication"

      - release:
          filters:
            branches:
              only:
                - main
          service_directory: "authentication"

      - send-test-coverage-reports:
          requires:
            - verify
            - release
          service_directory: "authentication"

      - update-ecs-service:
          requires:
            - release
          service_name: "authentication"
