
orbs:
  codecov: codecov/codecov@3.2.3
  aws-cli: circleci/aws-cli@1.3
  aws-ecs: circleci/aws-ecs@2.0
  queue: eddiewebb/queue@volatile

version: 2.1

executors:
  ubuntu-vm:
    machine:
      image: ubuntu-2204:2022.07.1
      docker_layer_caching: true

  openjdk-image:
    docker:
      - image: cimg/openjdk:11.0

  python-image:
    docker:
      - image: 'cimg/python:3.9.1'

parameters:
  run-sales-tax-workflow:
    type: boolean
    default: false
  run-files-workflow:
    type: boolean
    default: false
  run-api-gateway-workflow:
    type: boolean
    default: false
  run-discovery-service-workflow:
    type: boolean
    default: false
  run-sales-tax-rates-workflow:
    type: boolean
    default: false

jobs:
  package-dependency:
    parameters:
      service_directory:
        type: string
        default: ""

    working_directory: ~/complyt_work_directory/<<parameters.service_directory>>
    executor: ubuntu-vm
    steps:
      - checkout:
          path: ~/complyt_work_directory
      - run:
          name: Execute
          command: ./mvnw clean package -Dmaven.test.skip
      - persist_to_workspace:
          root: ~/complyt_work_directory
          paths:
            - <<parameters.service_directory>>/target/*.jar

  verify:
    parameters:
      service_directory:
        type: string
        default: ""

    working_directory: ~/complyt_work_directory/<<parameters.service_directory>>
    executor: ubuntu-vm
    steps:
      - checkout:
          path: ~/complyt_work_directory
      - attach_workspace:
          at: ~/complyt_work_directory
      - run:
          name: Execute
          command: ./mvnw clean verify
      - persist_to_workspace:
          root: target
          paths:
            - coverage-reports
            - failsafe-reports
            - surefire-reports
            - site

#  wait:
#    docker:
#      - image: circleci/node:10
#    steps:
#      - queue/until_front_of_line:
#          only-on-branch: "*"
#          time: '10'
#      - run: echo "This job will not overlap"

  release:
    parameters:
      service_directory:
        type: string
        default: ""
      branch_name:
        type: string
        default: ""
    working_directory: ~/complyt_work_directory/<<parameters.service_directory>>
    executor: ubuntu-vm

    steps:
      - checkout:
          path: ~/complyt_work_directory
      - attach_workspace:
          at: ~/complyt_work_directory
      - add_ssh_keys:
          fingerprints:
            - "8d:a9:53:20:ea:7a:b2:1d:e5:d8:af:d4:fc:e0:81:16"

      - run:
          name: Export image tag
          command: |
            image_tag=$(grep -m2 '<version>' pom.xml | tail -n1 | sed -n 's/.*<version>\([0-9.]*\).*<\/version>.*/\1/p')
            export IMAGE_TAG=$image_tag
            env >> bash.env

      - run:
          name: Release
          command: |
            PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
            NEXT_DEVELOPMENT_VERSION=$(echo "$PROJECT_VERSION" | awk -F'[-.]' '{print $1"."($2+1)".0-SNAPSHOT"}')
            git checkout -b "<<parameters.branch_name>>-$PROJECT_VERSION"
            ./mvnw --settings ../.circleci/settings.xml clean release:prepare -X -DdevelopmentVersion=$NEXT_DEVELOPMENT_VERSION
            ./mvnw --settings ../.circleci/settings.xml release:perform
            git checkout eyal/com-235-api-services-versioning-management
            git pull origin eyal/com-235-api-services-versioning-management
            git merge --no-edit "<<parameters.branch_name>>-$PROJECT_VERSION"
            git commit --amend -m "[skip ci]"
            git push --set-upstream origin eyal/com-235-api-services-versioning-management
            git push --delete origin "<<parameters.branch_name>>-$PROJECT_VERSION"

      - persist_to_workspace:
          root: .
          paths:
            - bash.env

      - persist_to_workspace:
          root: target
          paths:
            - coverage-test-service
            - failsafe-test-service
            - surefire-test-service
            - site

  send-test-coverage-reports:
    parameters:
      service_directory:
        type: string
        default: ""

    working_directory: ~/complyt_work_directory/<<parameters.service_directory>>
    executor: openjdk-image
    steps:
      - checkout:
          path: ~/complyt_work_directory
      - attach_workspace:
          at: target
      - run:
          name: Save test results
          command: |
            mkdir -p test-results
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} test-results/ \;
          when: always
      - store_test_results:
          path: test-results/
      - codecov/upload:
          file: target/site/jacoco-ut/jacoco.xml
          token: CODECOV_TOKEN
          flags: <<parameters.service_directory>>

  update-ecs-service:
    parameters:
      service_name:
        type: string
        default: ""

    working_directory: ~/complyt_work_directory/<<parameters.service_name>>
    executor: python-image
    steps:
      - checkout:
          path: ~/complyt_work_directory
      - attach_workspace:
          at: .
      - run:
          name: Extract image tag and set it as env variable
          command: |
            image_tag=$(grep "IMAGE_TAG" bash.env | cut -d'=' -f2)
            echo "container=<<parameters.service_name>>-container, tag='${image_tag}'"
            echo "export IMAGE_TAG='${image_tag}'" >> $BASH_ENV
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - aws-ecs/update-service:
          cluster-name: "production"
          container-image-name-updates: "container=<<parameters.service_name>>-container, tag=${IMAGE_TAG}"
          family: "<<parameters.service_name>>-task-definition"
          service-name: "<<parameters.service_name>>-service"

  block:
    docker:
      - image: circleci/node:10
    parameters:
      to_block:
        type: boolean
        default: true
    steps:
    - queue/until_front_of_line:
        block-workflow: <<parameters.to_block>>

workflows:
#  sales-tax-workflow:
#    when: << pipeline.parameters.run-sales-tax-workflow >>
#    jobs:
#      - verify:
#          filters:
#            branches:
#              only:
#                - /^(main.+|(?!main).*)$/
#          service_directory: "sales-tax"
#
#      - release:
#          service_directory: "sales-tax"
#          filters:
#            branches:
#              only:
#                - main
#
#      - send-test-coverage-reports:
#          requires:
#            - verify
#            - release
#          service_directory: "sales-tax"
#
#      - update-ecs-service:
#          requires:
#            - release
#          service_name: "sales-tax"

  files-workflow:
    when: << pipeline.parameters.run-files-workflow >>
    jobs:
#      - verify:
#          filters:
#            branches:
#              only:
#                - /^(main.+|(?!main).*)$/
#          service_directory: "files"

      - release:
          service_directory: "files"
          branch_name: "files-workflow-release"
          filters:
            branches:
              only:
                - /^(main.+|(?!main).*)$/

      - send-test-coverage-reports:
          requires:
#            - verify
            - release
          service_directory: "files"

      - update-ecs-service:
          requires:
            - release
          service_name: "files"

  api-gateway-workflow:
    when: << pipeline.parameters.run-api-gateway-workflow >>
    jobs:
      - package-dependency:
          name: package-sales-tax
          service_directory: "sales-tax"
      - package-dependency:
          name: package-sales-tax-rates
          service_directory: "sales-tax-rates"
      - package-dependency:
          name: package-discovery-service
          service_directory: "discovery-service"
      - package-dependency:
          name: package-files
          service_directory: "files"

#      - verify:
#          filters:
#            branches:
#              only:
#                - /^(main.+|(?!main).*)$/
#          requires:
#            - package-sales-tax
#            - package-sales-tax-rates
#            - package-discovery-service
#            - package-files
#          service_directory: "api-gateway"

      - release:
          requires:
            - package-sales-tax
            - package-sales-tax-rates
            - package-discovery-service
            - package-files
          filters:
            branches:
              only:
                - /^(main.+|(?!main).*)$/
          service_directory: "api-gateway"
          branch_name: "api-gateway-workflow-release"


      - send-test-coverage-reports:
          requires:
#            - verify
            - release
          service_directory: "api-gateway"

      - update-ecs-service:
          requires:
            - release
          service_name: "api-gateway"

#  discovery-service-workflow:
#    when: << pipeline.parameters.run-discovery-service-workflow >>
#    jobs:
#      - verify:
#          filters:
#            branches:
#              only:
#                - /^(main.+|(?!main).*)$/
#          service_directory: "discovery-service"
#
#      - release:
#          filters:
#            branches:
#              only:
#                - main
#          service_directory: "discovery-service"
#
#      - send-test-coverage-reports:
#          requires:
#            - verify
#            - release
#          service_directory: "discovery-service"
#
#      # We update all the services that run Discovery Services
#      - update-ecs-service:
#          requires:
#            - release
#          service_name: "discovery-service-az-1a"
#
#      - update-ecs-service:
#          requires:
#            - release
#          service_name: "discovery-service-az-1b"
#
#  sales-tax-rates-workflow:
#    when: << pipeline.parameters.run-sales-tax-rates-workflow >>
#    jobs:
#      - verify:
#          filters:
#            branches:
#              only:
#                - /^(main.+|(?!main).*)$/
#          service_directory: "sales-tax-rates"
#
#      - release:
#          filters:
#            branches:
#              only:
#                - main
#          service_directory: "sales-tax-rates"
#
#      - send-test-coverage-reports:
#          requires:
#            - verify
#            - release
#          service_directory: "sales-tax-rates"
#
#      - update-ecs-service:
#          requires:
#            - release
#          service_name: "sales-tax-rates"