package com.complyt.domain.nexus;

public enum TimeFrame {
    CURRENT_AND_PREVIOUS_TAXABLE_YEAR,
    CURRENT_AND_PREVIOUS_CALENDER_YEAR,
    PREVIOUS_TWELVE_MONTHS,
    PREVIOUS_CALENDER_YEAR,
    YEAR_FROM_SEPTEMBER_TO_SEPTEMBER
}
