spring:
  profiles:
    active:
      # local - to run your application directly on the OS
      # local-docker - to run your application in a docker container
      # connected to a MongoDB that runs in a docker container as well.
      # To run in this profile execute ./mvnw clean package docker:build docker:run
      # production - This is for production only
      - production
      # fastTax - to use FastTax service
      # stubFastTax - to use stub method of FastTax
      # zipTax - to use Zip Tax Service
      - fastTax

logging:
  level:
    root: INFO
    web: DEBUG
    org:
      springframework:
        security: DEBUG
    reactor:
      netty:
        http: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"



