package com.complyt.domain;

import java.util.HashMap;
import java.util.Map;

public interface StatesMap {
    Map<String, String> statesToCollections = new HashMap<>() {{
        put("AL", CollectionsNames.ALABAMA);
        put("Alabama", CollectionsNames.ALABAMA);
        put("AK", CollectionsNames.ALASKA);
        put("Alaska", CollectionsNames.ALASKA);
        put("AZ", CollectionsNames.ARIZONA);
        put("Arizona", CollectionsNames.ARIZONA);
        put("AR", CollectionsNames.ARKANSAS);
        put("Arkansas", CollectionsNames.ARKANSAS);
        put("CA", CollectionsNames.CALIFORNIA);
        put("California", CollectionsNames.CALIFORNIA);
        put("CT", CollectionsNames.CONNECTICUT);
        put("Connecticut", CollectionsNames.CONNECTICUT);
        put("CO", CollectionsNames.COLORADO);
        put("Colorado", CollectionsNames.COLORADO);
        put("DE", CollectionsNames.DELAWARE);
        put("Delaware", CollectionsNames.DELAWARE);
        put("DC", CollectionsNames.DISTRICT_OF_COLOMBIA);
        put("District of Columbia", CollectionsNames.DISTRICT_OF_COLOMBIA);
        put("FL", CollectionsNames.FLORIDA);
        put("Florida", CollectionsNames.FLORIDA);
        put("GA", CollectionsNames.GEORGIA);
        put("Georgia", CollectionsNames.GEORGIA);
        put("HI", CollectionsNames.HAWAII);
        put("Hawaii", CollectionsNames.HAWAII);
        put("ID", CollectionsNames.IDAHO);
        put("Idaho", CollectionsNames.IDAHO);
        put("IL", CollectionsNames.ILLINOIS);
        put("Illinois", CollectionsNames.ILLINOIS);
        put("IN", CollectionsNames.INDIANA);
        put("Indiana", CollectionsNames.INDIANA);
        put("IA", CollectionsNames.IOWA);
        put("Iowa", CollectionsNames.IOWA);
        put("KS", CollectionsNames.KANSAS);
        put("Kansas", CollectionsNames.KANSAS);
        put("KY", CollectionsNames.KENTUCKY);
        put("Kentucky", CollectionsNames.KENTUCKY);
        put("LA", CollectionsNames.LOUISIANA);
        put("Louisiana", CollectionsNames.LOUISIANA);
        put("ME", CollectionsNames.MAINE);
        put("Maine", CollectionsNames.MAINE);
        put("MD", CollectionsNames.MARYLAND);
        put("Maryland", CollectionsNames.MARYLAND);
        put("MI", CollectionsNames.MICHIGAN);
        put("Michigan", CollectionsNames.MICHIGAN);
        put("MN", CollectionsNames.MINNESOTA);
        put("Minnesota", CollectionsNames.MINNESOTA);
        put("MS", CollectionsNames.MISSISSIPPI);
        put("Mississippi", CollectionsNames.MISSISSIPPI);
        put("MO", CollectionsNames.MISSOURI);
        put("Missouri", CollectionsNames.MISSOURI);
        put("MT", CollectionsNames.MONTANA);
        put("Montana", CollectionsNames.MONTANA);
        put("NE", CollectionsNames.NEBRASKA);
        put("Nebraska", CollectionsNames.NEBRASKA);
        put("NV", CollectionsNames.NEVADA);
        put("Nevada", CollectionsNames.NEVADA);
        put("NH", CollectionsNames.NEW_HAMPSHIRE);
        put("New Hampshire", CollectionsNames.NEW_HAMPSHIRE);
        put("NJ", CollectionsNames.NEW_JERSEY);
        put("New Jersey", CollectionsNames.NEW_JERSEY);
        put("NM", CollectionsNames.NEW_MEXICO);
        put("New Mexico", CollectionsNames.NEW_MEXICO);
        put("NY", CollectionsNames.NEW_YORK);
        put("New York", CollectionsNames.NEW_YORK);
        put("NC", CollectionsNames.NORTH_CAROLINA);
        put("North Carolina", CollectionsNames.NORTH_CAROLINA);
        put("ND", CollectionsNames.NORTH_DAKOTA);
        put("North Dakota", CollectionsNames.NORTH_DAKOTA);
        put("OH", CollectionsNames.OHIO);
        put("Ohio", CollectionsNames.OHIO);
        put("OK", CollectionsNames.OKLAHOMA);
        put("Oklahoma", CollectionsNames.OKLAHOMA);
        put("OR", CollectionsNames.OREGON);
        put("Oregon", CollectionsNames.OREGON);
        put("PA", CollectionsNames.PENNSYLVANIA);
        put("Pennsylvania", CollectionsNames.PENNSYLVANIA);
        put("RI", CollectionsNames.RHODE_ISLAND);
        put("Rhode Island", CollectionsNames.RHODE_ISLAND);
        put("SC", CollectionsNames.SOUTH_CAROLINA);
        put("South Carolina", CollectionsNames.SOUTH_CAROLINA);
        put("SD", CollectionsNames.SOUTH_DAKOTA);
        put("South Dakota", CollectionsNames.SOUTH_DAKOTA);
        put("TN", CollectionsNames.TENNESSEE);
        put("Tennessee", CollectionsNames.TENNESSEE);
        put("TX", CollectionsNames.TEXAS);
        put("Texas", CollectionsNames.TEXAS);
        put("UT", CollectionsNames.UTAH);
        put("Utah", CollectionsNames.UTAH);
        put("VT", CollectionsNames.VERMONT);
        put("Vermont", CollectionsNames.VERMONT);
        put("VA", CollectionsNames.VIRGINIA);
        put("Virginia", CollectionsNames.VIRGINIA);
        put("WA", CollectionsNames.WASHINGTON);
        put("Washington", CollectionsNames.WASHINGTON);
        put("WV", CollectionsNames.WEST_VIRGINIA);
        put("West Virginia", CollectionsNames.WEST_VIRGINIA);
        put("WI", CollectionsNames.WISCONSIN);
        put("Wisconsin", CollectionsNames.WISCONSIN);
    }};
}