spring.application.name: discovery-service
server.port: ${PORT:8761}

# We set these two parameters to prevent from the Discovery Service to look for a discovery service
# (because this is who he is) and fetch its registry
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  service-url:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false

logging:
  level:
    com:
      netflix:
        eureka: off
        discovery: off