spring:
  data:
    mongodb:
      uri: ${mongo-uri}
      database: ${db-name}

eureka:
  client:
    serviceUrl:
      defaultZone: ${discovery-service-uri}
  instance:
    prefer-ip-address: true

logging:
  level:
    root: DEBUG
    web: DEBUG
    org:
      springframework:
        security: INFO
    reactor:
      netty:
        http: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"