spring.application.name: sales-tax
server.port: ${PORT:9898}

spring.profiles.active:
  - @activeEnv@
  - @activeTaxClient@
  - @activeCurrencyClient@

# Eureka HealthCheck
# Make sure that a microservice will not be listed 'UP' in eureka before it passes the healthcheck.
# Will mark it as 'UP' after it's ready to serve requests.
eureka:
  client:
    healthcheck:
      enabled: true

# There is no need to check the vault health in runtime - we use fast-fail so the service will not start if vault is unavailable.
management:
  health:
    vault:
      enabled: false

# Observability
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.tracing.sampling.probability: 1.0


spring:
  data:
    mongodb:
      uuid-representation: standard

# Set a TCP connection timeout of 200ms between microservices - so feign will do a retry if microservice is down
reactive:
  feign:
    client:
      config:
        default:
          options:
            connectTimeoutMillis: 200
