spring:
  profiles:
    active:
      # local - to run your application directly on the OS
      # local-docker - to run your application in a docker container
      # connected to a MongoDB that runs in a docker container as well.
      # To run in this profile execute ./mvnw clean package docker:build docker:run
      # production - This is for production only
      - production
      # fastTax - to use FastTax service
      # stubFastTax - to use stub method of FastTax
      # zipTax - to use Zip Tax Service
      - fastTax
  cloud.vault:
    enabled: true
    application-name: sales-tax-service
    host: vault-cluster-public-vault-81338a8e.8cda002f.z1.hashicorp.cloud
    port: 8200
    scheme: https
    namespace: admin
    fail-fast: true
    config:
      lifecycle:
        enabled: true
        min-renewal: 10s
        expiry-threshold: 1m
    authentication: APPROLE
    app-role:
      role-id: 9114c06e-5b8b-e828-62f0-69ff1c139ecc
      secret-id: 49ca2477-a4b9-5fc4-3ce0-d5d68e90fdf1
      role: sales-tax-service-role
      app-role-path: approle
    generic:
      enabled: true
      backend: secret
    kv:
      enabled: true
      default-context:
    database:
      enabled: true
      role: complyt-db-rw
      backend: database

spring.config.import: vault://

logging:
  level:
    root: INFO
    web: DEBUG
    org:
      springframework:
        security: DEBUG
    reactor:
      netty:
        http: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"



