eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  data:
    mongodb:
      uri: mongodb+srv://${spring.datasource.username}:${spring.datasource.password}@tomer.39drrff.mongodb.net/sales_tax

logging:
  level:
    root: info