auth0.audience: null

eureka:
  client:
    should-unregister-on-shutdown: true
    initial-instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 15
    register-with-eureka: true
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 30


logging:
  level:
    root: info

spring:
  cloud:
    vault:
      enabled: false
  data:
    mongodb:
      database: sales_tax