spring:
  profiles:
    active:
      # local - to run your application directly on the OS
      # local-docker - to run your application in a docker container
      # connected to a MongoDB that runs in a docker container as well.
      # To run in this profile execute ./mvnw clean package docker:build docker:run
      # production - This is for production only
      - production
      # fastTax - to use FastTax service
      # stubFastTax - to use stub method of FastTax
      # zipTax - to use Zip Tax Service
      - fastTax
  cloud:
    vault:
      kv:
        default-context:
      application-name: sales-tax-service
      host: vault-cluster-public-vault-81338a8e.8cda002f.z1.hashicorp.cloud
      port: 8200
      scheme: https
      namespace: admin
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      database:
        enabled: true
        role: complyt-db-rw
        backend: database
        username-property: db.username
        password-property: db.password

logging:
  level:
    root: INFO
    web: DEBUG
    org:
      springframework:
        security: DEBUG
    reactor:
      netty:
        http: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"



