package com.complyt.business.collection_fetcher;

import java.util.HashMap;
import java.util.Map;

public interface UsaStatesMap {
    Map<String, String> statesToCollections = new HashMap<>() {{
        put("AL", CollectionsNames.ALABAMA);
        put("ALABAMA", CollectionsNames.ALABAMA);
        put("AK", CollectionsNames.ALASKA);
        put("ALASKA", CollectionsNames.ALASKA);
        put("AZ", CollectionsNames.ARIZONA);
        put("ARIZONA", CollectionsNames.ARIZONA);
        put("AR", CollectionsNames.ARKANSAS);
        put("ARKANSAS", CollectionsNames.ARKANSAS);
        put("CA", CollectionsNames.CALIFORNIA);
        put("CALIFORNIA", CollectionsNames.CALIFORNIA);
        put("CT", CollectionsNames.CONNECTICUT);
        put("CONNECTICUT", CollectionsNames.CONNECTICUT);
        put("CO", CollectionsNames.COLORADO);
        put("COLORADO", CollectionsNames.COLORADO);
        put("DE", CollectionsNames.DELAWARE);
        put("DELAWARE", CollectionsNames.DELAWARE);
        put("DC", CollectionsNames.DISTRICT_OF_COLOMBIA);
        put("DISTRICT OF COLUMBIA", CollectionsNames.DISTRICT_OF_COLOMBIA);
        put("FL", CollectionsNames.FLORIDA);
        put("FLORIDA", CollectionsNames.FLORIDA);
        put("GA", CollectionsNames.GEORGIA);
        put("GEORGIA", CollectionsNames.GEORGIA);
        put("HI", CollectionsNames.HAWAII);
        put("HAWAII", CollectionsNames.HAWAII);
        put("ID", CollectionsNames.IDAHO);
        put("IDAHO", CollectionsNames.IDAHO);
        put("IL", CollectionsNames.ILLINOIS);
        put("ILLINOIS", CollectionsNames.ILLINOIS);
        put("IN", CollectionsNames.INDIANA);
        put("INDIANA", CollectionsNames.INDIANA);
        put("IA", CollectionsNames.IOWA);
        put("IOWA", CollectionsNames.IOWA);
        put("KS", CollectionsNames.KANSAS);
        put("KANSAS", CollectionsNames.KANSAS);
        put("KY", CollectionsNames.KENTUCKY);
        put("KENTUCKY", CollectionsNames.KENTUCKY);
        put("LA", CollectionsNames.LOUISIANA);
        put("LOUISIANA", CollectionsNames.LOUISIANA);
        put("MA", CollectionsNames.MASSACHUSETTS);
        put("MASSACHUSETTS", CollectionsNames.MASSACHUSETTS);
        put("ME", CollectionsNames.MAINE);
        put("MAINE", CollectionsNames.MAINE);
        put("MD", CollectionsNames.MARYLAND);
        put("MARYLAND", CollectionsNames.MARYLAND);
        put("MI", CollectionsNames.MICHIGAN);
        put("MICHIGAN", CollectionsNames.MICHIGAN);
        put("MN", CollectionsNames.MINNESOTA);
        put("MINNESOTA", CollectionsNames.MINNESOTA);
        put("MS", CollectionsNames.MISSISSIPPI);
        put("MISSISSIPPI", CollectionsNames.MISSISSIPPI);
        put("MO", CollectionsNames.MISSOURI);
        put("MISSOURI", CollectionsNames.MISSOURI);
        put("MT", CollectionsNames.MONTANA);
        put("MONTANA", CollectionsNames.MONTANA);
        put("NE", CollectionsNames.NEBRASKA);
        put("NEBRASKA", CollectionsNames.NEBRASKA);
        put("NV", CollectionsNames.NEVADA);
        put("NEVADA", CollectionsNames.NEVADA);
        put("NH", CollectionsNames.NEW_HAMPSHIRE);
        put("NEW HAMPSHIRE", CollectionsNames.NEW_HAMPSHIRE);
        put("NJ", CollectionsNames.NEW_JERSEY);
        put("NEW JERSEY", CollectionsNames.NEW_JERSEY);
        put("NM", CollectionsNames.NEW_MEXICO);
        put("NEW MEXICO", CollectionsNames.NEW_MEXICO);
        put("NY", CollectionsNames.NEW_YORK);
        put("NEW YORK", CollectionsNames.NEW_YORK);
        put("NC", CollectionsNames.NORTH_CAROLINA);
        put("NORTH CAROLINA", CollectionsNames.NORTH_CAROLINA);
        put("ND", CollectionsNames.NORTH_DAKOTA);
        put("NORTH DAKOTA", CollectionsNames.NORTH_DAKOTA);
        put("OH", CollectionsNames.OHIO);
        put("OHIO", CollectionsNames.OHIO);
        put("OK", CollectionsNames.OKLAHOMA);
        put("OKLAHOMA", CollectionsNames.OKLAHOMA);
        put("OR", CollectionsNames.OREGON);
        put("OREGON", CollectionsNames.OREGON);
        put("PA", CollectionsNames.PENNSYLVANIA);
        put("PENNSYLVANIA", CollectionsNames.PENNSYLVANIA);
        put("RI", CollectionsNames.RHODE_ISLAND);
        put("RHODE ISLAND", CollectionsNames.RHODE_ISLAND);
        put("SC", CollectionsNames.SOUTH_CAROLINA);
        put("SOUTH CAROLINA", CollectionsNames.SOUTH_CAROLINA);
        put("SD", CollectionsNames.SOUTH_DAKOTA);
        put("SOUTH DAKOTA", CollectionsNames.SOUTH_DAKOTA);
        put("TN", CollectionsNames.TENNESSEE);
        put("TENNESSEE", CollectionsNames.TENNESSEE);
        put("TX", CollectionsNames.TEXAS);
        put("TEXAS", CollectionsNames.TEXAS);
        put("UT", CollectionsNames.UTAH);
        put("UTAH", CollectionsNames.UTAH);
        put("VT", CollectionsNames.VERMONT);
        put("VERMONT", CollectionsNames.VERMONT);
        put("VA", CollectionsNames.VIRGINIA);
        put("VIRGINIA", CollectionsNames.VIRGINIA);
        put("WA", CollectionsNames.WASHINGTON);
        put("WASHINGTON", CollectionsNames.WASHINGTON);
        put("WASHINGTON DC", CollectionsNames.DISTRICT_OF_COLOMBIA);
        put("WASHINGTON D.C", CollectionsNames.DISTRICT_OF_COLOMBIA);
        put("WASHINGTON D.C.", CollectionsNames.DISTRICT_OF_COLOMBIA);
        put("WV", CollectionsNames.WEST_VIRGINIA);
        put("WEST VIRGINIA", CollectionsNames.WEST_VIRGINIA);
        put("WI", CollectionsNames.WISCONSIN);
        put("WISCONSIN", CollectionsNames.WISCONSIN);
        put("WY", CollectionsNames.WYOMING);
        put("WYOMING", CollectionsNames.WYOMING);
    }};
}