package com.complyt.business.address;

import java.util.HashMap;
import java.util.Map;

public interface StateMap {
        Map<String, String> statesToStandartizedState = new HashMap<>() {{
            put("AL", "Alabama");
            put("ALABAMA", "Alabama");
            put("AK", "Alaska");
            put("ALASKA", "Alaska");
            put("AZ", "Arizona");
            put("ARIZONA", "Arizona");
            put("AR", "Arkansas");
            put("ARKANSAS", "Arkansas");
            put("CA", "California");
            put("CALIFORNIA", "California");
            put("CT", "Connecticut");
            put("CONNECTICUT", "Connecticut");
            put("CO", "Colorado");
            put("COLORADO", "Colorado");
            put("DE", "Delaware");
            put("DELAWARE", "Delaware");
            put("DC", "District of Columbia");
            put("DISTRICT OF COLUMBIA", "District of Columbia");
            put("FL", "Florida");
            put("FLORIDA", "Florida");
            put("GA", "Georgia");
            put("GEORGIA", "Georgia");
            put("HI", "Hawaii");
            put("HAWAII", "Hawaii");
            put("ID", "Idaho");
            put("IDAHO", "Idaho");
            put("IL", "Illinois");
            put("ILLINOIS", "Illinois");
            put("IN", "Indiana");
            put("INDIANA", "Indiana");
            put("IA", "Iowa");
            put("IOWA", "Iowa");
            put("KS", "Kansas");
            put("KANSAS", "Kansas");
            put("KY", "Kentucky");
            put("KENTUCKY", "Kentucky");
            put("LA", "Louisiana");
            put("LOUISIANA", "Louisiana");
            put("MA", "Massachusetts");
            put("MASSACHUSETTS", "Massachusetts");
            put("ME", "Maine");
            put("MAINE", "Maine");
            put("MD", "Maryland");
            put("MARYLAND", "Maryland");
            put("MI", "Michigan");
            put("MICHIGAN", "Michigan");
            put("MN", "Minnesota");
            put("MINNESOTA", "Minnesota");
            put("MS", "Mississippi");
            put("MISSISSIPPI", "Mississippi");
            put("MO", "Missouri");
            put("MISSOURI", "Missouri");
            put("MT", "Montana");
            put("MONTANA", "Montana");
            put("NE", "Nebraska");
            put("NEBRASKA", "Nebraska");
            put("NV", "Nevada");
            put("NEVADA", "Nevada");
            put("NH", "New Hampshire");
            put("NEW HAMPSHIRE", "New Hampshire");
            put("NJ", "New Jersey");
            put("NEW JERSEY", "New Jersey");
            put("NM", "New Mexico");
            put("NEW MEXICO", "New Mexico");
            put("NY", "New York");
            put("NEW YORK", "New York");
            put("NC", "North Carolina");
            put("NORTH CAROLINA", "North Carolina");
            put("ND", "North Dakota");
            put("NORTH DAKOTA", "North Dakota");
            put("OH", "Ohio");
            put("OHIO", "Ohio");
            put("OK", "Oklahoma");
            put("OKLAHOMA", "Oklahoma");
            put("OR", "Oregon");
            put("OREGON", "Oregon");
            put("PA", "Pennsylvania");
            put("PENNSYLVANIA", "Pennsylvania");
            put("RI", "Rhode Island");
            put("RHODE ISLAND", "Rhode Island");
            put("SC", "South Carolina");
            put("SOUTH CAROLINA", "South Carolina");
            put("SD", "South Dakota");
            put("SOUTH DAKOTA", "South Dakota");
            put("TN", "Tennessee");
            put("TENNESSEE", "Tennessee");
            put("TX", "Texas");
            put("TEXAS", "Texas");
            put("UT", "Utah");
            put("UTAH", "Utah");
            put("VT", "Vermont");
            put("VERMONT", "Vermont");
            put("VA", "Virginia");
            put("VIRGINIA", "Virginia");
            put("WA", "Washington");
            put("WASHINGTON", "Washington");
            put("WASHINGTON DC", "District of Columbia");
            put("WASHINGTON D.C", "District of Columbia");
            put("WASHINGTON D.C.", "District of Columbia");
            put("WV", "West Virginia");
            put("WEST VIRGINIA", "West Virginia");
            put("WI", "Wisconsin");
            put("WISCONSIN", "Wisconsin");
            put("WY", "Wyoming");
            put("WYOMING", "Wyoming");
        }};
}