package com.complyt.business.address;

import java.util.HashMap;
import java.util.Map;

public interface StateMap {
    Map<String, String> statesToStandartizedState = new HashMap<>() {{
        put("AL", "Alabama");
        put("ALABAMA", "Alabama");
        put("ALABAMMA", "Alabama");
        put("ALABMA", "Alabama");
        put("AK", "Alaska");
        put("ALASKA", "Alaska");
        put("ALASCA", "Alaska");
        put("ALASKAA", "Alaska");
        put("AZ", "Arizona");
        put("ARIZONA", "Arizona");
        put("ARIZONNA", "Arizona");
        put("AR", "Arkansas");
        put("ARKANSAS", "Arkansas");
        put("ARKANSA", "Arkansas");
        put("ARKANSS", "Arkansas");
        put("CA", "California");
        put("CALIFORNIA", "California");
        put("CALIFONIA", "California");
        put("CALIFORNIAA", "California");
        put("CT", "Connecticut");
        put("CONNECTICUT", "Connecticut");
        put("CONNECTICUTT", "Connecticut");
        put("CONNETICUT", "Connecticut");
        put("CO", "Colorado");
        put("COLORADO", "Colorado");
        put("COLORODO", "Colorado");
        put("COLORDAO", "Colorado");
        put("DE", "Delaware");
        put("DELAWARE", "Delaware");
        put("DELLAWARE", "Delaware");
        put("DELAWERE", "Delaware");
        put("DC", "District of Columbia");
        put("DISTRICT OF COLUMBIA", "District of Columbia");
        put("DISTRICT  OF  COLUMBIA", "District of Columbia");
        put("DISTRICT  OF COLUMBIA", "District of Columbia");
        put("DISTRICT OF  COLUMBIA", "District of Columbia");
        put("DISTRICT OF COLUMBA", "District of Columbia");
        put("FL", "Florida");
        put("FLORIDA", "Florida");
        put("FLORIDIA", "Florida");
        put("FLORDIA", "Florida");
        put("GA", "Georgia");
        put("GEORGIA", "Georgia");
        put("GEORIGA", "Georgia");
        put("GEORGIAA", "Georgia");
        put("HI", "Hawaii");
        put("HAWAII", "Hawaii");
        put("HAWAI", "Hawaii");
        put("HAWI", "Hawaii");
        put("ID", "Idaho");
        put("IDAHO", "Idaho");
        put("IDAHOE", "Idaho");
        put("IDAAHO", "Idaho");
        put("IL", "Illinois");
        put("ILLINOIS", "Illinois");
        put("ILLINIOS", "Illinois");
        put("ILLINOISS", "Illinois");
        put("IN", "Indiana");
        put("INDIANA", "Indiana");
        put("INDINNA", "Indiana");
        put("INDIENA", "Indiana");
        put("IA", "Iowa");
        put("IOWA", "Iowa");
        put("IOAW", "Iowa");
        put("IWA", "Iowa");
        put("KS", "Kansas");
        put("KANSAS", "Kansas");
        put("KANAS", "Kansas");
        put("KANSASS", "Kansas");
        put("KY", "Kentucky");
        put("KENTUCKY", "Kentucky");
        put("KENTUKY", "Kentucky");
        put("KENTUCKKY", "Kentucky");
        put("LA", "Louisiana");
        put("LOUISIANA", "Louisiana");
        put("LOUISANA", "Louisiana");
        put("LOUISIANNA", "Louisiana");
        put("MA", "Massachusetts");
        put("MASSACHUSETTS", "Massachusetts");
        put("MASSACHUSSETS", "Massachusetts");
        put("MASSACHUSSETTS", "Massachusetts");
        put("ME", "Maine");
        put("MAINE", "Maine");
        put("MAIINE", "Maine");
        put("MAIN", "Maine");
        put("MD", "Maryland");
        put("MARYLAND", "Maryland");
        put("MARYLANDD", "Maryland");
        put("MARYLANNDD", "Maryland");
        put("MI", "Michigan");
        put("MICHIGAN", "Michigan");
        put("MICHIGON", "Michigan");
        put("MICHAGAN", "Michigan");
        put("MN", "Minnesota");
        put("MINNESOTA", "Minnesota");
        put("MINESOTA", "Minnesota");
        put("MINNESOTTA", "Minnesota");
        put("MS", "Mississippi");
        put("MISSISSIPPI", "Mississippi");
        put("MISSISIPPI", "Mississippi");
        put("MISSSISSIPPI", "Mississippi");
        put("MO", "Missouri");
        put("MISSOURI", "Missouri");
        put("MISOURI", "Missouri");
        put("MISSOURRI", "Missouri");
        put("MT", "Montana");
        put("MONTANA", "Montana");
        put("MONTANNA", "Montana");
        put("MONTENA", "Montana");
        put("NE", "Nebraska");
        put("NEBRASKA", "Nebraska");
        put("NEBRASCA", "Nebraska");
        put("NEBRAKA", "Nebraska");
        put("NV", "Nevada");
        put("NEVADA", "Nevada");
        put("NEVVADA", "Nevada");
        put("NEVADAA", "Nevada");
        put("NH", "New Hampshire");
        put("NEW HAMPSHIRE", "New Hampshire");
        put("NEW HAMPSIRE", "New Hampshire");
        put("NEW  HAMPSHIRE", "New Hampshire");
        put("NJ", "New Jersey");
        put("NEW JERSEY", "New Jersey");
        put("NEW JERSY", "New Jersey");
        put("NEW JERZEY", "New Jersey");
        put("NM", "New Mexico");
        put("NEW MEXICO", "New Mexico");
        put("NEW  MEXICO", "New Mexico");
        put("NEW MEXICOO", "New Mexico");
        put("NY", "New York");
        put("NEW YORK", "New York");
        put("NEW  YORK", "New York");
        put("NEW YOKR", "New York");
        put("NEW YOURK", "New York");
        put("NC", "North Carolina");
        put("NORTH CAROLINA", "North Carolina");
        put("NORTH  CAROLINA", "North Carolina");
        put("NORTH CAROLNA", "North Carolina");
        put("ND", "North Dakota");
        put("NORTH DAKOTA", "North Dakota");
        put("NORTH  DAKOTA", "North Dakota");
        put("NORTH DAKOA", "North Dakota");
        put("OH", "Ohio");
        put("OHIO", "Ohio");
        put("OHHIO", "Ohio");
        put("OK", "Oklahoma");
        put("OKLAHOMA", "Oklahoma");
        put("OKLOHOMA", "Oklahoma");
        put("OKLAHOMAA", "Oklahoma");
        put("OR", "Oregon");
        put("OREGON", "Oregon");
        put("OREGONN", "Oregon");
        put("ORAGON", "Oregon");
        put("PA", "Pennsylvania");
        put("PENNSYLVANIA", "Pennsylvania");
        put("PENNSLYVANIA", "Pennsylvania");
        put("PENNSYLVANNIA", "Pennsylvania");
        put("RI", "Rhode Island");
        put("RHODE ISLAND", "Rhode Island");
        put("RODE ISLAND", "Rhode Island");
        put("RHODE  ISLAND", "Rhode Island");
        put("SC", "South Carolina");
        put("SOUTH CAROLINA", "South Carolina");
        put("SOUTH  CAROLINA", "South Carolina");
        put("SOUTH CAROLLINA", "South Carolina");
        put("SD", "South Dakota");
        put("SOUTH DAKOTA", "South Dakota");
        put("SOUTH  DAKOTA", "South Dakota");
        put("SOUTH DAKOTAA", "South Dakota");
        put("TN", "Tennessee");
        put("TENNESSEE", "Tennessee");
        put("TENNESEE", "Tennessee");
        put("TENNESSE", "Tennessee");
        put("TX", "Texas");
        put("TEXAS", "Texas");
        put("TEXASS", "Texas");
        put("TEXAAS", "Texas");
        put("UT", "Utah");
        put("UTAH", "Utah");
        put("UTAHH", "Utah");
        put("UTHA", "Utah");
        put("VT", "Vermont");
        put("VERMONT", "Vermont");
        put("VERMOT", "Vermont");
        put("VERMONTT", "Vermont");
        put("VA", "Virginia");
        put("VIRGINIA", "Virginia");
        put("VIRGINNIA", "Virginia");
        put("VIGINIA ", "Virginia");
        put("WA", "Washington");
        put("WASHINGTON", "Washington");
        put("WASHINTON", "Washington");
        put("WASHINGTONN", "Washington");
        put("WASHINGTON DC", "District of Columbia");
        put("WASHINGTON D.C", "District of Columbia");
        put("WASHINGTON D.C.", "District of Columbia");
        put("WV", "West Virginia");
        put("WEST VIRGINIA", "West Virginia");
        put("WEST  VIRGINIA", "West Virginia");
        put("WEST VIRGINNIA", "West Virginia");
        put("WI", "Wisconsin");
        put("WISCONSIN", "Wisconsin");
        put("WISCONNSIN", "Wisconsin");
        put("WISCONSIN  ", "Wisconsin");
        put("WY", "Wyoming");
        put("WYOMING", "Wyoming");
        put("WYOOMING", "Wyoming");
        put("WIOMING", "Wyoming");
    }};
}