package com.complyt.v1.models.nexus;

public enum TimeFrameDto {
    CURRENT_TAXABLE_YEAR,
    CURRENT_CALENDER_YEAR,
    PREVIOUS_TWELVE_MONTHS,
    PREVIOUS_CALENDER_YEAR,
    YEAR_FROM_SEPTEMBER_TO_SEPTEMBER
}
