package com.example.complyt.domain;

import com.complyt.domain.CollectionsNames;
import com.complyt.domain.StatesMap;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class StatesMapTest {

    @Test
    void testToStatesMap() {
        Assertions.assertEquals(StatesMap.statesToCollections.get("AL"), CollectionsNames.ALABAMA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Alabama"),CollectionsNames.ALABAMA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("AK"), CollectionsNames.ALASKA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Alaska"), CollectionsNames.ALASKA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("AZ"), CollectionsNames.ARIZONA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Arizona"), CollectionsNames.ARIZONA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("AR"), CollectionsNames.ARKANSAS);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Arkansas"), CollectionsNames.ARKANSAS);
        Assertions.assertEquals(StatesMap.statesToCollections.get("CA"), CollectionsNames.CALIFORNIA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("California"), CollectionsNames.CALIFORNIA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("CT"), CollectionsNames.CONNECTICUT);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Connecticut"), CollectionsNames.CONNECTICUT);
        Assertions.assertEquals(StatesMap.statesToCollections.get("CO"), CollectionsNames.COLORADO);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Colorado"), CollectionsNames.COLORADO);
        Assertions.assertEquals(StatesMap.statesToCollections.get("DE"), CollectionsNames.DELAWARE);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Delaware"), CollectionsNames.DELAWARE);
        Assertions.assertEquals(StatesMap.statesToCollections.get("DC"), CollectionsNames.DISTRICT_OF_COLOMBIA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("District of Columbia"), CollectionsNames.DISTRICT_OF_COLOMBIA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("FL"), CollectionsNames.FLORIDA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Florida"), CollectionsNames.FLORIDA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("GA"), CollectionsNames.GEORGIA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Georgia"), CollectionsNames.GEORGIA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("HI"), CollectionsNames.HAWAII);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Hawaii"), CollectionsNames.HAWAII);
        Assertions.assertEquals(StatesMap.statesToCollections.get("ID"), CollectionsNames.IDAHO);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Idaho"), CollectionsNames.IDAHO);
        Assertions.assertEquals(StatesMap.statesToCollections.get("IL"), CollectionsNames.ILLINOIS);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Illinois"), CollectionsNames.ILLINOIS);
        Assertions.assertEquals(StatesMap.statesToCollections.get("IN"), CollectionsNames.INDIANA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Indiana"), CollectionsNames.INDIANA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("IA"), CollectionsNames.IOWA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Iowa"), CollectionsNames.IOWA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("KS"), CollectionsNames.KANSAS);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Kansas"), CollectionsNames.KANSAS);
        Assertions.assertEquals(StatesMap.statesToCollections.get("KY"), CollectionsNames.KENTUCKY);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Kentucky"), CollectionsNames.KENTUCKY);
        Assertions.assertEquals(StatesMap.statesToCollections.get("LA"), CollectionsNames.LOUISIANA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Louisiana"), CollectionsNames.LOUISIANA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("ME"), CollectionsNames.MAINE);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Maine"), CollectionsNames.MAINE);
        Assertions.assertEquals(StatesMap.statesToCollections.get("MD"), CollectionsNames.MARYLAND);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Maryland"), CollectionsNames.MARYLAND);
        Assertions.assertEquals(StatesMap.statesToCollections.get("MI"), CollectionsNames.MICHIGAN);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Michigan"), CollectionsNames.MICHIGAN);
        Assertions.assertEquals(StatesMap.statesToCollections.get("MN"), CollectionsNames.MINNESOTA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Minnesota"), CollectionsNames.MINNESOTA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("MS"), CollectionsNames.MISSISSIPPI);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Mississippi"), CollectionsNames.MISSISSIPPI);
        Assertions.assertEquals(StatesMap.statesToCollections.get("MO"), CollectionsNames.MISSOURI);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Missouri"), CollectionsNames.MISSOURI);
        Assertions.assertEquals(StatesMap.statesToCollections.get("MT"), CollectionsNames.MONTANA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Montana"), CollectionsNames.MONTANA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("NE"), CollectionsNames.NEBRASKA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Nebraska"), CollectionsNames.NEBRASKA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("NV"), CollectionsNames.NEVADA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Nevada"), CollectionsNames.NEVADA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("NH"), CollectionsNames.NEW_HAMPSHIRE);
        Assertions.assertEquals(StatesMap.statesToCollections.get("New Hampshire"), CollectionsNames.NEW_HAMPSHIRE);
        Assertions.assertEquals(StatesMap.statesToCollections.get("NJ"), CollectionsNames.NEW_JERSEY);
        Assertions.assertEquals(StatesMap.statesToCollections.get("New Jersey"), CollectionsNames.NEW_JERSEY);
        Assertions.assertEquals(StatesMap.statesToCollections.get("NM"), CollectionsNames.NEW_MEXICO);
        Assertions.assertEquals(StatesMap.statesToCollections.get("New Mexico"), CollectionsNames.NEW_MEXICO);
        Assertions.assertEquals(StatesMap.statesToCollections.get("NY"), CollectionsNames.NEW_YORK);
        Assertions.assertEquals(StatesMap.statesToCollections.get("New York"), CollectionsNames.NEW_YORK);
        Assertions.assertEquals(StatesMap.statesToCollections.get("NC"), CollectionsNames.NORTH_CAROLINA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("North Carolina"), CollectionsNames.NORTH_CAROLINA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("ND"), CollectionsNames.NORTH_DAKOTA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("North Dakota"), CollectionsNames.NORTH_DAKOTA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("OH"), CollectionsNames.OHIO);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Ohio"), CollectionsNames.OHIO);
        Assertions.assertEquals(StatesMap.statesToCollections.get("OK"), CollectionsNames.OKLAHOMA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Oklahoma"), CollectionsNames.OKLAHOMA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("OR"), CollectionsNames.OREGON);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Oregon"), CollectionsNames.OREGON);
        Assertions.assertEquals(StatesMap.statesToCollections.get("PA"), CollectionsNames.PENNSYLVANIA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Pennsylvania"), CollectionsNames.PENNSYLVANIA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("RI"), CollectionsNames.RHODE_ISLAND);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Rhode Island"), CollectionsNames.RHODE_ISLAND);
        Assertions.assertEquals(StatesMap.statesToCollections.get("SC"), CollectionsNames.SOUTH_CAROLINA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("South Carolina"), CollectionsNames.SOUTH_CAROLINA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("SD"), CollectionsNames.SOUTH_DAKOTA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("South Dakota"), CollectionsNames.SOUTH_DAKOTA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("TN"), CollectionsNames.TENNESSEE);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Tennessee"), CollectionsNames.TENNESSEE);
        Assertions.assertEquals(StatesMap.statesToCollections.get("TX"), CollectionsNames.TEXAS);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Texas"), CollectionsNames.TEXAS);
        Assertions.assertEquals(StatesMap.statesToCollections.get("UT"), CollectionsNames.UTAH);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Utah"), CollectionsNames.UTAH);
        Assertions.assertEquals(StatesMap.statesToCollections.get("VT"), CollectionsNames.VERMONT);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Vermont"), CollectionsNames.VERMONT);
        Assertions.assertEquals(StatesMap.statesToCollections.get("VA"), CollectionsNames.VIRGINIA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Virginia"), CollectionsNames.VIRGINIA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("WA"), CollectionsNames.WASHINGTON);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Washington"), CollectionsNames.WASHINGTON);
        Assertions.assertEquals(StatesMap.statesToCollections.get("WV"), CollectionsNames.WEST_VIRGINIA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("West Virginia"), CollectionsNames.WEST_VIRGINIA);
        Assertions.assertEquals(StatesMap.statesToCollections.get("WI"), CollectionsNames.WISCONSIN);
        Assertions.assertEquals(StatesMap.statesToCollections.get("Wisconsin"), CollectionsNames.WISCONSIN);
    }
}
