spring.application.name: sales-tax-rates

server.port: ${PORT:9090}

spring.profiles.active:
  - @activeEnv@
  - @activeTaxClient@

# Spring Cloud Vault configuration
# To understand what every field stands for visit
# https://cloud.spring.io/spring-cloud-vault/reference/html/
spring.cloud.vault:
  enabled: true
  application-name: sales-tax-rates-service
  host: ${VAULT_HOST}
  port: 8200
  scheme: https
  namespace: admin
  fail-fast: true
  config:
    lifecycle:
      enabled: true
      min-renewal: 10s
      expiry-threshold: 1m
  authentication: APPROLE
  app-role:
    role-id: ${VAULT_ROLE_ID}
    secret-id: ${VAULT_SECRET_ID}
    role: ${VAULT_ROLE}
    app-role-path: approle
  kv:
    enabled: true
    default-context:
  database:
    enabled: true
    role: ${VAULT_DB_ROLE}
    backend: database

spring.config.import: vault://

auth0.audience: ${audience}

# This property sets the issuer URI
# for the application to interact with the Resource Server for authentication and authorization purposes
spring.security.oauth2.resourceserver.jwt.issuer-uri: ${issuer-uri}

# Observability
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.tracing.sampling.probability: 1.0

spring:
  data:
    mongodb:
      uuid-representation: standard
