eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    should-unregister-on-shutdown: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30

spring:
  data:
    mongodb:
      uri: ${mongo-uri}
      database: ${db-name}

logging:
  level:
    root: info