auth0.audience: null

eureka:
  client:
    should-unregister-on-shutdown: true
    register-with-eureka: true
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 30
    hostname: localhost
    instance-id: localhost:${server.port}


logging:
  level:
    root: info

spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://host.docker.internal:8080/realms/test-realm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8080/realms/test-realm

spring:
  cloud:
    vault:
      enabled: false
  data:
    mongodb:
      database: sales_tax_rates