eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    should-unregister-on-shutdown: true
    initial-instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 15
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30

# Spring Cloud Vault configuration
# To understand what every field stands for visit
# https://cloud.spring.io/spring-cloud-vault/reference/html/
spring.cloud.vault:
  enabled: true
<<<<<<< HEAD
<<<<<<< HEAD
  application-name: sales-tax-rates-service${ecs_cluster_name:}
=======
  application-name: sales-tax-rates-service{ecs_cluster_name:}
>>>>>>> 142c5389 (feat: added mono.defer to rates)
=======
  application-name: sales-tax-rates-service${ecs_cluster_name:}
>>>>>>> 20373e7e (feat: added terraform yaml configuration)
  host: ${VAULT_HOST}
  port: 8200
  scheme: https
  namespace: admin
  fail-fast: true
  config:
    lifecycle:
      enabled: true
      min-renewal: 10s
      expiry-threshold: 1m
  authentication: APPROLE
  app-role:
    role-id: ${VAULT_ROLE_ID}
    secret-id: ${VAULT_SECRET_ID}
    role: ${VAULT_ROLE}
    app-role-path: approle
  kv:
    enabled: true
    default-context:
  database:
    enabled: true
    role: ${VAULT_DB_ROLE}
    backend: database

spring.config.import: vault://

auth0.audience: ${audience}

# This property sets the issuer URI
# for the application to interact with the Resource Server for authentication and authorization purposes
spring.security.oauth2.resourceserver.jwt.issuer-uri: ${issuer-uri}

spring:
  data:
    mongodb:
      uri: ${mongo-uri}
      database: ${db-name}

logging:
  level:
    root: info