eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761//eureka

auth0:
  audience: https://sales-tax-service/

# This property sets the issuer URI
# for the application to interact with the Resource Server for authentication and authorization purposes
spring.security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: https://development-complyt.us.auth0.com/