package com.complyt.business.address;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class StatesMapTest {

    @Test
    void testToStatesMap() {
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("AL"), "Alabama");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("ALABAMA"), "Alabama");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("AK"), "Alaska");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("ALASKA"), "Alaska");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("AZ"), "Arizona");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("ARIZONA"), "Arizona");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("AR"), "Arkansas");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("ARKANSAS"), "Arkansas");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("CA"), "California");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("CALIFORNIA"), "California");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("CT"), "Connecticut");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("CONNECTICUT"), "Connecticut");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("CO"), "Colorado");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("COLORADO"), "Colorado");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("DE"), "Delaware");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("DELAWARE"), "Delaware");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("DC"), "District of Columbia");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("DISTRICT OF COLUMBIA"), "District of Columbia");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("FL"), "Florida");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("FLORIDA"), "Florida");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("GA"), "Georgia");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("GEORGIA"), "Georgia");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("HI"), "Hawaii");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("HAWAII"), "Hawaii");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("ID"), "Idaho");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("IDAHO"), "Idaho");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("IL"), "Illinois");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("ILLINOIS"), "Illinois");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("IN"), "Indiana");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("INDIANA"), "Indiana");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("IA"), "Iowa");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("IOWA"), "Iowa");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("KS"), "Kansas");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("KANSAS"), "Kansas");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("KY"), "Kentucky");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("KENTUCKY"), "Kentucky");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("LA"), "Louisiana");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("LOUISIANA"), "Louisiana");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("MA"), "Massachusetts");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("MASSACHUSETTS"), "Massachusetts");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("ME"), "Maine");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("MAINE"), "Maine");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("MD"), "Maryland");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("MARYLAND"), "Maryland");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("MI"), "Michigan");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("MICHIGAN"), "Michigan");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("MN"), "Minnesota");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("MINNESOTA"), "Minnesota");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("MS"), "Mississippi");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("MISSISSIPPI"), "Mississippi");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("MO"), "Missouri");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("MISSOURI"), "Missouri");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("MT"), "Montana");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("MONTANA"), "Montana");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("NE"), "Nebraska");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("NEBRASKA"), "Nebraska");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("NV"), "Nevada");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("NEVADA"), "Nevada");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("NH"), "New Hampshire");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("NEW HAMPSHIRE"), "New Hampshire");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("NJ"), "New Jersey");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("NEW JERSEY"), "New Jersey");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("NM"), "New Mexico");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("NEW MEXICO"), "New Mexico");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("NY"), "New York");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("NEW YORK"), "New York");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("NC"), "North Carolina");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("NORTH CAROLINA"), "North Carolina");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("ND"), "North Dakota");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("NORTH DAKOTA"), "North Dakota");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("OH"), "Ohio");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("OHIO"), "Ohio");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("OK"), "Oklahoma");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("OKLAHOMA"), "Oklahoma");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("OR"), "Oregon");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("OREGON"), "Oregon");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("PA"), "Pennsylvania");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("PENNSYLVANIA"), "Pennsylvania");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("RI"), "Rhode Island");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("RHODE ISLAND"), "Rhode Island");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("SC"), "South Carolina");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("SOUTH CAROLINA"), "South Carolina");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("SD"), "South Dakota");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("SOUTH DAKOTA"), "South Dakota");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("TN"), "Tennessee");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("TENNESSEE"), "Tennessee");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("TX"), "Texas");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("TEXAS"), "Texas");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("UT"), "Utah");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("UTAH"), "Utah");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("VT"), "Vermont");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("VERMONT"), "Vermont");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("VA"), "Virginia");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("VIRGINIA"), "Virginia");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("WA"), "Washington");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("WASHINGTON"), "Washington");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("WASHINGTON DC"), "District of Columbia");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("WASHINGTON D.C"), "District of Columbia");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("WASHINGTON D.C."), "District of Columbia");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("WV"), "West Virginia");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("WEST VIRGINIA"), "West Virginia");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("WI"), "Wisconsin");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("WISCONSIN"), "Wisconsin");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("WY"), "Wyoming");
        Assertions.assertEquals(StateMap.statesToStandartizedState.get("WYOMING"), "Wyoming");
    }
}
